import { IQuizItem } from './types'

export const quizMocks = {
  en: [
    {
      id: 'qlang',
      type: 'language',
      question: 'Select language',
      description: 'Choose interface language',
      options: [
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Español' },
        { value: 'fr', label: 'Français' },
        { value: 'de', label: 'Deutsch' },
      ],
      transitions: [{ to: 'qt1' }],
    },
    {
      id: 'qt1',
      type: 'tile',
      question: 'Select your <gender>',
      description: 'We use this to personalize your quiz',
      options: [
        { value: 'female', label: '👩 Female' },
        { value: 'male', label: '👨 Male' },
        { value: 'other', label: '😉 Other' },
      ],
      transitions: [
        { to: 'q1f', when: { equals: 'female' } },
        { to: 'q1m', when: { equals: 'male' } },
        { to: 'q1o', when: { equals: 'other' } },
      ],
    },
    // Female branch
    {
      id: 'q1f',
      type: 'single',
      question: 'What is your age?',
      description: 'Select your age range to personalize recommendations',
      options: [
        { value: '18-24', label: '18-24 years' },
        { value: '25-29', label: '25-29 years' },
        { value: '30-39', label: '30-39 years' },
        { value: '40+', label: '40+ years' },
      ],
      transitions: [{ to: 'q2f' }],
    },
    {
      id: 'q2f',
      type: 'multiple',
      question: 'What do you <hate> the most in a book?',
      options: [
        { value: 'lack_logic', label: 'Lack of logic' },
        { value: 'lack_humor', label: 'Lack of humor' },
        { value: 'weak_characters', label: 'Weak characters' },
        { value: 'predictable', label: 'Predictable plot' },
      ],
      transitions: [{ to: 'q3f' }],
    },
    {
      id: 'q3f',
      type: 'bubble',
      question: 'What are your favorite <topics>?',
      options: [
        { value: 'action', label: '💃 Action' },
        { value: 'romance', label: '🥰 Romance' },
        { value: 'bad_boy', label: '🤠 Bad Boy' },
        { value: 'royal', label: '👑 Royal Obsession' },
      ],
      transitions: [{ to: 'q4f' }],
    },
    {
      id: 'q4f',
      type: 'single',
      question: 'What <color> is the sky?',
      options: [
        { value: 'blue', label: 'Blue' },
        { value: 'red', label: 'Red' },
        { value: 'green', label: 'Green' },
      ],
      transitions: [{ to: 'q5f' }],
    },
    {
      id: 'q5f',
      type: 'input',
      question: 'Capital of Spain?',
      options: [],
    },
    // Male branch (age-based flows, 5 steps total)
    {
      id: 'q1m',
      type: 'single',
      question: 'What is your age?',
      options: [
        { value: '18-24', label: '18-24 years' },
        { value: '25-29', label: '25-29 years' },
        { value: '30-39', label: '30-39 years' },
        { value: '40+', label: '40+ years' },
      ],
      transitions: [
        { to: 'q2m18', when: { equals: '18-24' } },
        { to: 'q2m25', when: { equals: '25-29' } },
        { to: 'q2m30', when: { equals: '30-39' } },
        { to: 'q2m40', when: { equals: '40+' } },
      ],
    },
    // 18-24
    {
      id: 'q2m18',
      type: 'bubble',
      question: 'What activities are you into right now?',
      description: 'Pick a few you like',
      options: [
        { value: 'gaming', label: '🎮 Gaming' },
        { value: 'gym', label: '💪 Gym' },
        { value: 'tech', label: '🧑‍💻 Tech & Gadgets' },
        { value: 'streetwear', label: '🧢 Streetwear' },
      ],
      transitions: [{ to: 'q3m18' }],
    },
    {
      id: 'q3m18',
      type: 'single',
      question: 'Pick a preferred content <genre>',
      options: [
        { value: 'action', label: 'Action' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'sports', label: 'Sports' },
        { value: 'comedy', label: 'Comedy' },
      ],
      transitions: [{ to: 'q4m18' }],
    },
    {
      id: 'q4m18',
      type: 'multiple',
      question: 'Which interests describe you best?',
      options: [
        { value: 'cars', label: 'Cars' },
        { value: 'fitness', label: 'Fitness' },
        { value: 'gadgets', label: 'Gadgets' },
        { value: 'travel', label: 'Travel' },
      ],
      transitions: [{ to: 'q5m18' }],
    },
    {
      id: 'q5m18',
      type: 'input',
      question: 'Your favorite team or brand?',
      options: [],
    },
    // 25-29
    {
      id: 'q2m25',
      type: 'bubble',
      question: 'What hobbies keep you engaged?',
      options: [
        { value: 'fitness', label: '💪 Fitness' },
        { value: 'coding', label: '🧑‍💻 Coding' },
        { value: 'photography', label: '📸 Photography' },
        { value: 'gaming', label: '🎮 Gaming' },
      ],
      transitions: [{ to: 'q3m25' }],
    },
    {
      id: 'q3m25',
      type: 'single',
      question: 'Preferred reading genre',
      options: [
        { value: 'thriller', label: 'Thriller' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'business', label: 'Business' },
        { value: 'action', label: 'Action' },
      ],
      transitions: [{ to: 'q4m25' }],
    },
    {
      id: 'q4m25',
      type: 'multiple',
      question: 'Pick areas you want to improve',
      options: [
        { value: 'career', label: 'Career' },
        { value: 'finance', label: 'Finance' },
        { value: 'health', label: 'Health' },
        { value: 'skills', label: 'Skills' },
      ],
      transitions: [{ to: 'q5m25' }],
    },
    {
      id: 'q5m25',
      type: 'input',
      question: 'Your current goal in one line?',
      options: [],
    },
    // 30-39
    {
      id: 'q2m30',
      type: 'bubble',
      question: 'What topics inspire you the <most>?',
      options: [
        { value: 'startups', label: '🚀 Startups' },
        { value: 'investing', label: '💹 Investing' },
        { value: 'parenting', label: '👨‍👩‍👧 Parenting' },
        { value: 'fitness', label: '💪 Fitness' },
      ],
      transitions: [{ to: 'q3m30' }],
    },
    {
      id: 'q3m30',
      type: 'single',
      question: 'Preferred reading genre',
      options: [
        { value: 'business', label: 'Business' },
        { value: 'history', label: 'History' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'thriller', label: 'Thriller' },
      ],
      transitions: [{ to: 'q4m30' }],
    },
    {
      id: 'q4m30',
      type: 'multiple',
      question: 'Pick your weekend activities',
      options: [
        { value: 'outdoors', label: 'Outdoors' },
        { value: 'diy', label: 'DIY' },
        { value: 'sports', label: 'Sports' },
        { value: 'family', label: 'Family time' },
      ],
      transitions: [{ to: 'q5m30' }],
    },
    {
      id: 'q5m30',
      type: 'input',
      question: 'Your main priority this year?',
      options: [],
    },
    // 40+
    {
      id: 'q2m40',
      type: 'bubble',
      question: 'What do you enjoy the <most>?',
      options: [
        { value: 'travel', label: '✈️ Travel' },
        { value: 'gardening', label: '🌱 Gardening' },
        { value: 'investing', label: '💹 Investing' },
        { value: 'sports', label: '🏈 Sports' },
      ],
      transitions: [{ to: 'q3m40' }],
    },
    {
      id: 'q3m40',
      type: 'single',
      question: 'Preferred reading genre',
      options: [
        { value: 'history', label: 'History' },
        { value: 'thriller', label: 'Thriller' },
        { value: 'business', label: 'Business' },
        { value: 'scifi', label: 'Sci‑Fi' },
      ],
      transitions: [{ to: 'q4m40' }],
    },
    {
      id: 'q4m40',
      type: 'multiple',
      question: 'Pick areas of interest',
      options: [
        { value: 'health', label: 'Health' },
        { value: 'finance', label: 'Finance' },
        { value: 'culture', label: 'Culture' },
        { value: 'technology', label: 'Technology' },
      ],
      transitions: [{ to: 'q5m40' }],
    },
    {
      id: 'q5m40',
      type: 'input',
      question: 'A destination on your bucket list?',
      options: [],
    },
    // Other branch
    {
      id: 'q1o',
      type: 'single',
      question: 'Pick a preferred UI <theme>',
      options: [
        { value: 'light', label: 'Light' },
        { value: 'dark', label: 'Dark' },
        { value: 'system', label: 'System' },
      ],
      transitions: [{ to: 'q2o' }],
    },
    {
      id: 'q2o',
      type: 'multiple',
      question: 'Select the <fruits>:',
      options: [
        { value: 'apple', label: 'Apple' },
        { value: 'carrot', label: 'Carrot' },
        { value: 'banana', label: 'Banana' },
        { value: 'potato', label: 'Potato' },
      ],
      transitions: [{ to: 'q3o' }],
    },
    {
      id: 'q3o',
      type: 'bubble',
      question: 'What are your favorite topics?',
      options: [
        { value: 'action', label: '💃 Action' },
        { value: 'romance', label: '🥰 Romance' },
        { value: 'bad_boy', label: '🤠 Bad Boy' },
        { value: 'royal', label: '👑 Royal Obsession' },
      ],
      transitions: [{ to: 'q4o' }],
    },
    {
      id: 'q4o',
      type: 'single',
      question: 'What color is the sky?',
      options: [
        { value: 'blue', label: 'Blue' },
        { value: 'red', label: 'Red' },
        { value: 'green', label: 'Green' },
      ],
      transitions: [{ to: 'q5o' }],
    },
    {
      id: 'q5o',
      type: 'input',
      question: 'Capital of Italy?',
      options: [],
    },
  ],
  es: [
    {
      id: 'qlang',
      type: 'language',
      question: 'Selecciona el idioma',
      description: 'Elige el idioma de la interfaz',
      options: [
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Español' },
        { value: 'fr', label: 'Français' },
        { value: 'de', label: 'Deutsch' },
      ],
      transitions: [{ to: 'qt1' }],
    },
    {
      id: 'qt1',
      type: 'tile',
      question: 'Selecciona tu género',
      description: 'Lo usamos para personalizar tu cuestionario',
      options: [
        { value: 'female', label: '👩 Mujer' },
        { value: 'male', label: '👨 Hombre' },
        { value: 'other', label: '😉 Otro' },
      ],
      transitions: [
        { to: 'q1f', when: { equals: 'female' } },
        { to: 'q1m', when: { equals: 'male' } },
        { to: 'q1o', when: { equals: 'other' } },
      ],
    },
    // Rama femenina
    {
      id: 'q1f',
      type: 'single',
      question: '¿Cuál es tu edad?',
      description:
        'Selecciona tu rango de edad para personalizar las recomendaciones',
      options: [
        { value: '18-24', label: '18-24 años' },
        { value: '25-29', label: '25-29 años' },
        { value: '30-39', label: '30-39 años' },
        { value: '40+', label: '40+ años' },
      ],
      transitions: [{ to: 'q2f' }],
    },
    {
      id: 'q2f',
      type: 'multiple',
      question: '¿Qué odias más en un libro?',
      options: [
        { value: 'lack_logic', label: 'Falta de lógica' },
        { value: 'lack_humor', label: 'Falta de humor' },
        { value: 'weak_characters', label: 'Personajes débiles' },
        { value: 'predictable', label: 'Trama predecible' },
      ],
      transitions: [{ to: 'q3f' }],
    },
    {
      id: 'q3f',
      type: 'bubble',
      question: '¿Cuáles son tus <temas> favoritos?',
      options: [
        { value: 'action', label: '💃 Acción' },
        { value: 'romance', label: '🥰 Romance' },
        { value: 'bad_boy', label: '🤠 Chico Malo' },
        { value: 'royal', label: '👑 Obsesión real' },
      ],
      transitions: [{ to: 'q4f' }],
    },
    {
      id: 'q4f',
      type: 'single',
      question: '¿De qué color es el cielo?',
      options: [
        { value: 'blue', label: 'Azul' },
        { value: 'red', label: 'Rojo' },
        { value: 'green', label: 'Verde' },
      ],
      transitions: [{ to: 'q5f' }],
    },
    {
      id: 'q5f',
      type: 'input',
      question: '¿Capital de Alemania?',
      options: [],
    },
    // Rama masculina (por edad)
    {
      id: 'q1m',
      type: 'single',
      question: '¿Cuál es tu edad?',
      options: [
        { value: '18-24', label: '18-24 años' },
        { value: '25-29', label: '25-29 años' },
        { value: '30-39', label: '30-39 años' },
        { value: '40+', label: '40+ años' },
      ],
      transitions: [
        { to: 'q2m18', when: { equals: '18-24' } },
        { to: 'q2m25', when: { equals: '25-29' } },
        { to: 'q2m30', when: { equals: '30-39' } },
        { to: 'q2m40', when: { equals: '40+' } },
      ],
    },
    // 18-24
    {
      id: 'q2m18',
      type: 'bubble',
      question: '¿Qué actividades te gustan ahora?',
      description: 'Elige algunas que te gusten',
      options: [
        { value: 'gaming', label: '🎮 Gaming' },
        { value: 'gym', label: '💪 Gimnasio' },
        { value: 'tech', label: '🧑‍💻 Tecnología' },
        { value: 'streetwear', label: '🧢 Streetwear' },
      ],
      transitions: [{ to: 'q3m18' }],
    },
    {
      id: 'q3m18',
      type: 'single',
      question: 'Elige un género de <contenido>',
      options: [
        { value: 'action', label: 'Acción' },
        { value: 'scifi', label: 'Ciencia ficción' },
        { value: 'sports', label: 'Deportes' },
        { value: 'comedy', label: 'Comedia' },
      ],
      transitions: [{ to: 'q4m18' }],
    },
    {
      id: 'q4m18',
      type: 'multiple',
      question: '¿Qué intereses te describen mejor?',
      options: [
        { value: 'cars', label: 'Autos' },
        { value: 'fitness', label: 'Fitness' },
        { value: 'gadgets', label: 'Gadgets' },
        { value: 'travel', label: 'Viajes' },
      ],
      transitions: [{ to: 'q5m18' }],
    },
    {
      id: 'q5m18',
      type: 'input',
      question: '¿Tu equipo o marca favorita?',
      options: [],
    },
    // 25-29
    {
      id: 'q2m25',
      type: 'bubble',
      question: '¿Qué hobbies te mantienen activo?',
      options: [
        { value: 'fitness', label: '💪 Fitness' },
        { value: 'coding', label: '🧑‍💻 Programación' },
        { value: 'photography', label: '📸 Fotografía' },
        { value: 'gaming', label: '🎮 Gaming' },
      ],
      transitions: [{ to: 'q3m25' }],
    },
    {
      id: 'q3m25',
      type: 'single',
      question: 'Género de lectura preferido',
      options: [
        { value: 'thriller', label: 'Thriller' },
        { value: 'scifi', label: 'Ciencia ficción' },
        { value: 'business', label: 'Negocios' },
        { value: 'action', label: 'Acción' },
      ],
      transitions: [{ to: 'q4m25' }],
    },
    {
      id: 'q4m25',
      type: 'multiple',
      question: 'Elige áreas a mejorar',
      options: [
        { value: 'career', label: 'Carrera' },
        { value: 'finance', label: 'Finanzas' },
        { value: 'health', label: 'Salud' },
        { value: 'skills', label: 'Habilidades' },
      ],
      transitions: [{ to: 'q5m25' }],
    },
    {
      id: 'q5m25',
      type: 'input',
      question: '¿Tu objetivo actual en una frase?',
      options: [],
    },
    // 30-39
    {
      id: 'q2m30',
      type: 'bubble',
      question: '¿Qué temas te inspiran <más>?',
      options: [
        { value: 'startups', label: '🚀 Startups' },
        { value: 'investing', label: '💹 Inversión' },
        { value: 'parenting', label: '👨‍👩‍👧 Crianza' },
        { value: 'fitness', label: '💪 Fitness' },
      ],
      transitions: [{ to: 'q3m30' }],
    },
    {
      id: 'q3m30',
      type: 'single',
      question: 'Género de lectura preferido',
      options: [
        { value: 'business', label: 'Negocios' },
        { value: 'history', label: 'Historia' },
        { value: 'scifi', label: 'Ciencia ficción' },
        { value: 'thriller', label: 'Thriller' },
      ],
      transitions: [{ to: 'q4m30' }],
    },
    {
      id: 'q4m30',
      type: 'multiple',
      question: 'Elige actividades de fin de semana',
      options: [
        { value: 'outdoors', label: 'Aire libre' },
        { value: 'diy', label: 'DIY' },
        { value: 'sports', label: 'Deportes' },
        { value: 'family', label: 'Familia' },
      ],
      transitions: [{ to: 'q5m30' }],
    },
    {
      id: 'q5m30',
      type: 'input',
      question: '¿Tu prioridad principal este año?',
      options: [],
    },
    // 40+
    {
      id: 'q2m40',
      type: 'bubble',
      question: '¿Qué disfrutas <más>?',
      options: [
        { value: 'travel', label: '✈️ Viajar' },
        { value: 'gardening', label: '🌱 Jardinería' },
        { value: 'investing', label: '💹 Inversión' },
        { value: 'sports', label: '🏈 Deportes' },
      ],
      transitions: [{ to: 'q3m40' }],
    },
    {
      id: 'q3m40',
      type: 'single',
      question: 'Género de lectura preferido',
      options: [
        { value: 'history', label: 'Historia' },
        { value: 'thriller', label: 'Thriller' },
        { value: 'business', label: 'Negocios' },
        { value: 'scifi', label: 'Ciencia ficción' },
      ],
      transitions: [{ to: 'q4m40' }],
    },
    {
      id: 'q4m40',
      type: 'multiple',
      question: 'Elige áreas de interés',
      options: [
        { value: 'health', label: 'Salud' },
        { value: 'finance', label: 'Finanzas' },
        { value: 'culture', label: 'Cultura' },
        { value: 'technology', label: 'Tecnología' },
      ],
      transitions: [{ to: 'q5m40' }],
    },
    {
      id: 'q5m40',
      type: 'input',
      question: '¿Un destino de tu lista de deseos?',
      options: [],
    },
    // Rama otra
    {
      id: 'q1o',
      type: 'single',
      question: 'Elige un tema de UI <preferido>',
      options: [
        { value: 'light', label: 'Claro' },
        { value: 'dark', label: 'Oscuro' },
        { value: 'system', label: 'Sistema' },
      ],
      transitions: [{ to: 'q2o' }],
    },
    {
      id: 'q2o',
      type: 'multiple',
      question: 'Selecciona las <frutas>:',
      options: [
        { value: 'apple', label: 'Manzana' },
        { value: 'carrot', label: 'Zanahoria' },
        { value: 'banana', label: 'Plátano' },
        { value: 'potato', label: 'Patata' },
      ],
      transitions: [{ to: 'q3o' }],
    },
    {
      id: 'q3o',
      type: 'bubble',
      question: '¿Cuáles son tus temas favoritos?',
      options: [
        { value: 'action', label: '💃 Acción' },
        { value: 'romance', label: '🥰 Romance' },
        { value: 'bad_boy', label: '🤠 Chico Malo' },
        { value: 'royal', label: '👑 Obsesión real' },
      ],
      transitions: [{ to: 'q4o' }],
    },
    {
      id: 'q4o',
      type: 'single',
      question: '¿De qué color es el cielo?',
      options: [
        { value: 'blue', label: 'Azul' },
        { value: 'red', label: 'Rojo' },
        { value: 'green', label: 'Verde' },
      ],
      transitions: [{ to: 'q5o' }],
    },
    {
      id: 'q5o',
      type: 'input',
      question: '¿Capital de Italia?',
      options: [],
    },
  ],

  fr: [
    {
      id: 'qlang',
      type: 'language',
      question: 'Choisir la langue',
      description: 'Choisis la langue de l’interface',
      options: [
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Español' },
        { value: 'fr', label: 'Français' },
        { value: 'de', label: 'Deutsch' },
      ],
      transitions: [{ to: 'qt1' }],
    },
    {
      id: 'qt1',
      type: 'tile',
      question: 'Sélectionne ton genre',
      description: 'Nous l’utilisons pour personnaliser le quiz',
      options: [
        { value: 'female', label: '👩 Femme' },
        { value: 'male', label: '👨 Homme' },
        { value: 'other', label: '😉 Autre' },
      ],
      transitions: [
        { to: 'q1f', when: { equals: 'female' } },
        { to: 'q1m', when: { equals: 'male' } },
        { to: 'q1o', when: { equals: 'other' } },
      ],
    },
    // Branche féminine
    {
      id: 'q1f',
      type: 'single',
      question: 'Quel âge as-tu ?',
      description:
        'Sélectionne ta tranche d’âge pour personnaliser les recommandations',
      options: [
        { value: '18-24', label: '18-24 ans' },
        { value: '25-29', label: '25-29 ans' },
        { value: '30-39', label: '30-39 ans' },
        { value: '40+', label: '40+ ans' },
      ],
      transitions: [{ to: 'q2f' }],
    },
    {
      id: 'q2f',
      type: 'multiple',
      question: "Qu'est-ce que tu détestes le plus dans un livre ?",
      options: [
        { value: 'lack_logic', label: 'Manque de logique' },
        { value: 'lack_humor', label: "Manque d'humour" },
        { value: 'weak_characters', label: 'Personnages faibles' },
        { value: 'predictable', label: 'Intrigue prévisible' },
      ],
      transitions: [{ to: 'q3f' }],
    },
    {
      id: 'q3f',
      type: 'bubble',
      question: 'Quels sont tes <sujets> préférés ?',
      options: [
        { value: 'action', label: '💃 Action' },
        { value: 'romance', label: '🥰 Romance' },
        { value: 'bad_boy', label: '🤠 Bad Boy' },
        { value: 'royal', label: '👑 Obsession royale' },
      ],
      transitions: [{ to: 'q4f' }],
    },
    {
      id: 'q4f',
      type: 'single',
      question: 'De quelle couleur est le ciel ?',
      options: [
        { value: 'blue', label: 'Bleu' },
        { value: 'red', label: 'Rouge' },
        { value: 'green', label: 'Vert' },
      ],
      transitions: [{ to: 'q5f' }],
    },
    {
      id: 'q5f',
      type: 'input',
      question: 'Capitale de l’Espagne ?',
      options: [],
    },
    // Branche masculine (par âge, 5 étapes)
    {
      id: 'q1m',
      type: 'single',
      question: 'Quel âge as-tu ?',
      options: [
        { value: '18-24', label: '18-24 ans' },
        { value: '25-29', label: '25-29 ans' },
        { value: '30-39', label: '30-39 ans' },
        { value: '40+', label: '40+ ans' },
      ],
      transitions: [
        { to: 'q2m18', when: { equals: '18-24' } },
        { to: 'q2m25', when: { equals: '25-29' } },
        { to: 'q2m30', when: { equals: '30-39' } },
        { to: 'q2m40', when: { equals: '40+' } },
      ],
    },
    // 18-24
    {
      id: 'q2m18',
      type: 'bubble',
      question: 'Quelles activités t’attirent en ce moment ?',
      description: 'Choisis quelques‑unes qui te plaisent',
      options: [
        { value: 'gaming', label: '🎮 Gaming' },
        { value: 'gym', label: '💪 Salle de sport' },
        { value: 'tech', label: '🧑‍💻 Tech & gadgets' },
        { value: 'streetwear', label: '🧢 Streetwear' },
      ],
      transitions: [{ to: 'q3m18' }],
    },
    {
      id: 'q3m18',
      type: 'single',
      question: 'Choisis un genre de <contenu>',
      options: [
        { value: 'action', label: 'Action' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'sports', label: 'Sport' },
        { value: 'comedy', label: 'Comédie' },
      ],
      transitions: [{ to: 'q4m18' }],
    },
    {
      id: 'q4m18',
      type: 'multiple',
      question: 'Quels centres d’intérêt te décrivent le mieux ?',
      options: [
        { value: 'cars', label: 'Voitures' },
        { value: 'fitness', label: 'Fitness' },
        { value: 'gadgets', label: 'Gadgets' },
        { value: 'travel', label: 'Voyage' },
      ],
      transitions: [{ to: 'q5m18' }],
    },
    {
      id: 'q5m18',
      type: 'input',
      question: 'Ton équipe ou ta marque préférée ?',
      options: [],
    },
    // 25-29
    {
      id: 'q2m25',
      type: 'bubble',
      question: 'Quels loisirs te passionnent ?',
      options: [
        { value: 'fitness', label: '💪 Fitness' },
        { value: 'coding', label: '🧑‍💻 Code' },
        { value: 'photography', label: '📸 Photo' },
        { value: 'gaming', label: '🎮 Gaming' },
      ],
      transitions: [{ to: 'q3m25' }],
    },
    {
      id: 'q3m25',
      type: 'single',
      question: 'Genre de lecture préféré',
      options: [
        { value: 'thriller', label: 'Thriller' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'business', label: 'Business' },
        { value: 'action', label: 'Action' },
      ],
      transitions: [{ to: 'q4m25' }],
    },
    {
      id: 'q4m25',
      type: 'multiple',
      question: 'Choisis des axes d’amélioration',
      options: [
        { value: 'career', label: 'Carrière' },
        { value: 'finance', label: 'Finance' },
        { value: 'health', label: 'Santé' },
        { value: 'skills', label: 'Compétences' },
      ],
      transitions: [{ to: 'q5m25' }],
    },
    {
      id: 'q5m25',
      type: 'input',
      question: 'Ton objectif du moment en une phrase ?',
      options: [],
    },
    // 30-39
    {
      id: 'q2m30',
      type: 'bubble',
      question: 'Quels sujets t’inspirent le <plus> ?',
      options: [
        { value: 'startups', label: '🚀 Startups' },
        { value: 'investing', label: '💹 Investissement' },
        { value: 'parenting', label: '👨‍👩‍👧 Parentalité' },
        { value: 'fitness', label: '💪 Fitness' },
      ],
      transitions: [{ to: 'q3m30' }],
    },
    {
      id: 'q3m30',
      type: 'single',
      question: 'Genre de lecture préféré',
      options: [
        { value: 'business', label: 'Business' },
        { value: 'history', label: 'Histoire' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'thriller', label: 'Thriller' },
      ],
      transitions: [{ to: 'q4m30' }],
    },
    {
      id: 'q4m30',
      type: 'multiple',
      question: 'Choisis tes activités du week‑end',
      options: [
        { value: 'outdoors', label: 'Plein air' },
        { value: 'diy', label: 'DIY' },
        { value: 'sports', label: 'Sport' },
        { value: 'family', label: 'Temps en famille' },
      ],
      transitions: [{ to: 'q5m30' }],
    },
    {
      id: 'q5m30',
      type: 'input',
      question: 'Ta priorité principale cette année ?',
      options: [],
    },
    // 40+
    {
      id: 'q2m40',
      type: 'bubble',
      question: 'Qu’apprécies‑tu le <plus> ?',
      options: [
        { value: 'travel', label: '✈️ Voyage' },
        { value: 'gardening', label: '🌱 Jardinage' },
        { value: 'investing', label: '💹 Investissement' },
        { value: 'sports', label: '🏈 Sport' },
      ],
      transitions: [{ to: 'q3m40' }],
    },
    {
      id: 'q3m40',
      type: 'single',
      question: 'Genre de lecture préféré',
      options: [
        { value: 'history', label: 'Histoire' },
        { value: 'thriller', label: 'Thriller' },
        { value: 'business', label: 'Business' },
        { value: 'scifi', label: 'Sci‑Fi' },
      ],
      transitions: [{ to: 'q4m40' }],
    },
    {
      id: 'q4m40',
      type: 'multiple',
      question: 'Choisis des centres d’intérêt',
      options: [
        { value: 'health', label: 'Santé' },
        { value: 'finance', label: 'Finance' },
        { value: 'culture', label: 'Culture' },
        { value: 'technology', label: 'Technologie' },
      ],
      transitions: [{ to: 'q5m40' }],
    },
    {
      id: 'q5m40',
      type: 'input',
      question: 'Une destination sur ta bucket list ?',
      options: [],
    },
    // Branche autre
    {
      id: 'q1o',
      type: 'single',
      question: "Choisis un thème d'<interface> préféré",
      options: [
        { value: 'light', label: 'Clair' },
        { value: 'dark', label: 'Sombre' },
        { value: 'system', label: 'Système' },
      ],
      transitions: [{ to: 'q2o' }],
    },
    {
      id: 'q2o',
      type: 'multiple',
      question: 'Sélectionnez les <fruits> :',
      options: [
        { value: 'apple', label: 'Pomme' },
        { value: 'carrot', label: 'Carotte' },
        { value: 'banana', label: 'Banane' },
        { value: 'potato', label: 'Pomme de terre' },
      ],
      transitions: [{ to: 'q3o' }],
    },
    {
      id: 'q3o',
      type: 'bubble',
      question: 'Quels sont tes sujets préférés ?',
      options: [
        { value: 'action', label: '💃 Action' },
        { value: 'romance', label: '🥰 Romance' },
        { value: 'bad_boy', label: '🤠 Bad Boy' },
        { value: 'royal', label: '👑 Obsession royale' },
      ],
      transitions: [{ to: 'q4o' }],
    },
    {
      id: 'q4o',
      type: 'single',
      question: 'De quelle couleur est le ciel ?',
      options: [
        { value: 'blue', label: 'Bleu' },
        { value: 'red', label: 'Rouge' },
        { value: 'green', label: 'Vert' },
      ],
      transitions: [{ to: 'q5o' }],
    },
    {
      id: 'q5o',
      type: 'input',
      question: 'Capitale de l’Italie ?',
      options: [],
    },
  ],
  de: [
    {
      id: 'qlang',
      type: 'language',
      question: 'Sprache auswählen',
      description: 'Wähle die Interface‑Sprache',
      options: [
        { value: 'en', label: 'English' },
        { value: 'es', label: 'Español' },
        { value: 'fr', label: 'Français' },
        { value: 'de', label: 'Deutsch' },
      ],
      transitions: [{ to: 'qt1' }],
    },
    {
      id: 'qt1',
      type: 'tile',
      question: 'Wähle dein Geschlecht',
      description: 'Wir nutzen dies, um dein Quiz zu personalisieren',
      options: [
        { value: 'female', label: '👩 Frau' },
        { value: 'male', label: '👨 Mann' },
        { value: 'other', label: '😉 Andere' },
      ],
      transitions: [
        { to: 'q1f', when: { equals: 'female' } },
        { to: 'q1m', when: { equals: 'male' } },
        { to: 'q1o', when: { equals: 'other' } },
      ],
    },
    // Weiblicher Zweig
    {
      id: 'q1f',
      type: 'single',
      question: 'Wie alt bist du?',
      description:
        'Wähle deine Altersgruppe, um Empfehlungen zu personalisieren',
      options: [
        { value: '18-24', label: '18-24 Jahre' },
        { value: '25-29', label: '25-29 Jahre' },
        { value: '30-39', label: '30-39 Jahre' },
        { value: '40+', label: '40+ Jahre' },
      ],
      transitions: [{ to: 'q2f' }],
    },
    {
      id: 'q2f',
      type: 'multiple',
      question: 'Was hasst du an einem Buch am meisten?',
      options: [
        { value: 'lack_logic', label: 'Mangel an Logik' },
        { value: 'lack_humor', label: 'Mangel an Humor' },
        { value: 'weak_characters', label: 'Schwache Charaktere' },
        { value: 'predictable', label: 'Vorhersehbare Handlung' },
      ],
      transitions: [{ to: 'q3f' }],
    },
    {
      id: 'q3f',
      type: 'bubble',
      question: 'Was sind deine <Lieblingsthemen>?',
      options: [
        { value: 'action', label: '💃 Action' },
        { value: 'romance', label: '🥰 Romanze' },
        { value: 'bad_boy', label: '🤠 Bad Boy' },
        { value: 'royal', label: '👑 Königliche Obsession' },
      ],
      transitions: [{ to: 'q4f' }],
    },
    {
      id: 'q4f',
      type: 'single',
      question: 'Welche Farbe hat der Himmel?',
      options: [
        { value: 'blue', label: 'Blau' },
        { value: 'red', label: 'Rot' },
        { value: 'green', label: 'Grün' },
      ],
      transitions: [{ to: 'q5f' }],
    },
    {
      id: 'q5f',
      type: 'input',
      question: 'Hauptstadt von Spanien?',
      options: [],
    },
    // Männlicher Zweig (altersbasiert, 5 Schritte)
    {
      id: 'q1m',
      type: 'single',
      question: 'Wie alt bist du?',
      options: [
        { value: '18-24', label: '18-24 Jahre' },
        { value: '25-29', label: '25-29 Jahre' },
        { value: '30-39', label: '30-39 Jahre' },
        { value: '40+', label: '40+ Jahre' },
      ],
      transitions: [
        { to: 'q2m18', when: { equals: '18-24' } },
        { to: 'q2m25', when: { equals: '25-29' } },
        { to: 'q2m30', when: { equals: '30-39' } },
        { to: 'q2m40', when: { equals: '40+' } },
      ],
    },
    // 18-24
    {
      id: 'q2m18',
      type: 'bubble',
      question: 'Wofür begeisterst du dich gerade?',
      description: 'Wähle ein paar aus, die dir gefallen',
      options: [
        { value: 'gaming', label: '🎮 Gaming' },
        { value: 'gym', label: '💪 Fitnessstudio' },
        { value: 'tech', label: '🧑‍💻 Tech & Gadgets' },
        { value: 'streetwear', label: '🧢 Streetwear' },
      ],
      transitions: [{ to: 'q3m18' }],
    },
    {
      id: 'q3m18',
      type: 'single',
      question: 'Bevorzugtes Inhalts<genre>',
      options: [
        { value: 'action', label: 'Action' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'sports', label: 'Sport' },
        { value: 'comedy', label: 'Komödie' },
      ],
      transitions: [{ to: 'q4m18' }],
    },
    {
      id: 'q4m18',
      type: 'multiple',
      question: 'Welche Interessen passen am besten zu dir?',
      options: [
        { value: 'cars', label: 'Autos' },
        { value: 'fitness', label: 'Fitness' },
        { value: 'gadgets', label: 'Gadgets' },
        { value: 'travel', label: 'Reisen' },
      ],
      transitions: [{ to: 'q5m18' }],
    },
    {
      id: 'q5m18',
      type: 'input',
      question: 'Dein Lieblingsteam oder deine Marke?',
      options: [],
    },
    // 25-29
    {
      id: 'q2m25',
      type: 'bubble',
      question: 'Welche Hobbys beschäftigen dich?',
      options: [
        { value: 'fitness', label: '💪 Fitness' },
        { value: 'coding', label: '🧑‍💻 Programmieren' },
        { value: 'photography', label: '📸 Fotografie' },
        { value: 'gaming', label: '🎮 Gaming' },
      ],
      transitions: [{ to: 'q3m25' }],
    },
    {
      id: 'q3m25',
      type: 'single',
      question: 'Bevorzugtes Lesegenre',
      options: [
        { value: 'thriller', label: 'Thriller' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'business', label: 'Business' },
        { value: 'action', label: 'Action' },
      ],
      transitions: [{ to: 'q4m25' }],
    },
    {
      id: 'q4m25',
      type: 'multiple',
      question: 'Wähle Bereiche zur Verbesserung',
      options: [
        { value: 'career', label: 'Karriere' },
        { value: 'finance', label: 'Finanzen' },
        { value: 'health', label: 'Gesundheit' },
        { value: 'skills', label: 'Fähigkeiten' },
      ],
      transitions: [{ to: 'q5m25' }],
    },
    {
      id: 'q5m25',
      type: 'input',
      question: 'Dein aktuelles Ziel in einem Satz?',
      options: [],
    },
    // 30-39
    {
      id: 'q2m30',
      type: 'bubble',
      question: 'Welche Themen inspirieren dich am <meisten>?',
      options: [
        { value: 'startups', label: '🚀 Startups' },
        { value: 'investing', label: '💹 Investieren' },
        { value: 'parenting', label: '👨‍👩‍👧 Elternschaft' },
        { value: 'fitness', label: '💪 Fitness' },
      ],
      transitions: [{ to: 'q3m30' }],
    },
    {
      id: 'q3m30',
      type: 'single',
      question: 'Bevorzugtes Lesegenre',
      options: [
        { value: 'business', label: 'Business' },
        { value: 'history', label: 'Geschichte' },
        { value: 'scifi', label: 'Sci‑Fi' },
        { value: 'thriller', label: 'Thriller' },
      ],
      transitions: [{ to: 'q4m30' }],
    },
    {
      id: 'q4m30',
      type: 'multiple',
      question: 'Wähle deine Wochenendaktivitäten',
      options: [
        { value: 'outdoors', label: 'Draußen' },
        { value: 'diy', label: 'DIY' },
        { value: 'sports', label: 'Sport' },
        { value: 'family', label: 'Familienzeit' },
      ],
      transitions: [{ to: 'q5m30' }],
    },
    {
      id: 'q5m30',
      type: 'input',
      question: 'Deine Hauptpriorität dieses Jahr?',
      options: [],
    },
    // 40+
    {
      id: 'q2m40',
      type: 'bubble',
      question: 'Was macht dir am <meisten> Spaß?',
      options: [
        { value: 'travel', label: '✈️ Reisen' },
        { value: 'gardening', label: '🌱 Gärtnern' },
        { value: 'investing', label: '💹 Investieren' },
        { value: 'sports', label: '🏈 Sport' },
      ],
      transitions: [{ to: 'q3m40' }],
    },
    {
      id: 'q3m40',
      type: 'single',
      question: 'Bevorzugtes Lesegenre',
      options: [
        { value: 'history', label: 'Geschichte' },
        { value: 'thriller', label: 'Thriller' },
        { value: 'business', label: 'Business' },
        { value: 'scifi', label: 'Sci‑Fi' },
      ],
      transitions: [{ to: 'q4m40' }],
    },
    {
      id: 'q4m40',
      type: 'multiple',
      question: 'Wähle Interessensbereiche',
      options: [
        { value: 'health', label: 'Gesundheit' },
        { value: 'finance', label: 'Finanzen' },
        { value: 'culture', label: 'Kultur' },
        { value: 'technology', label: 'Technologie' },
      ],
      transitions: [{ to: 'q5m40' }],
    },
    {
      id: 'q5m40',
      type: 'input',
      question: 'Ein Ziel auf deiner Bucket List?',
      options: [],
    },
    // Anderer Zweig
    {
      id: 'q1o',
      type: 'single',
      question: 'Wähle ein bevorzugtes UI-<Theme>',
      options: [
        { value: 'light', label: 'Hell' },
        { value: 'dark', label: 'Dunkel' },
        { value: 'system', label: 'System' },
      ],
      transitions: [{ to: 'q2o' }],
    },
    {
      id: 'q2o',
      type: 'multiple',
      question: 'Wählen Sie die <Früchte> aus:',
      options: [
        { value: 'apple', label: 'Apfel' },
        { value: 'carrot', label: 'Karotte' },
        { value: 'banana', label: 'Banane' },
        { value: 'potato', label: 'Kartoffel' },
      ],
      transitions: [{ to: 'q3o' }],
    },
    {
      id: 'q3o',
      type: 'bubble',
      question: 'Was sind deine Lieblingsthemen?',
      options: [
        { value: 'action', label: '💃 Action' },
        { value: 'romance', label: '🥰 Romanze' },
        { value: 'bad_boy', label: '🤠 Bad Boy' },
        { value: 'royal', label: '👑 Königliche Obsession' },
      ],
      transitions: [{ to: 'q4o' }],
    },
    {
      id: 'q4o',
      type: 'single',
      question: 'Welche Farbe hat der Himmel?',
      options: [
        { value: 'blue', label: 'Blau' },
        { value: 'red', label: 'Rot' },
        { value: 'green', label: 'Grün' },
      ],
      transitions: [{ to: 'q5o' }],
    },
    {
      id: 'q5o',
      type: 'input',
      question: 'Hauptstadt von Italien?',
      options: [],
    },
  ],
} as unknown as Record<string, IQuizItem[]>
